### 댓글 작성
POST localhost:8080/api/board/1/comments
Content-Type: application/json

{
  "author": "댓글러",
  "content": "댓글이다.",
  "password": "12345678"

}

### 댓글 조회
GET localhost:8080/api/1/comments?page=1&size=15
Content-Type: application/json